name: spider

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - spider
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Spider branch
      uses: actions/checkout@v2
      with:
        ref: spider
    - name: Checkout Master branch
      uses: actions/checkout@v2
      with:
        ref: master
        path: data
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Create local changes
      run: |
        npm install
        node spider.js
    - name: Commit files
      id: commit
      run: |
        cd data
        git config --local user.email "soekibun+bot@gmail.com"
        git config --local user.name "ekibot"
        time=$(date "+%Y%m%d%H%M%S")
        git add . -v
        set +e
        git commit -m "Update at ${time}"
        cmt=$?
        set -e
        if [ $cmt -eq 0 ]; then
          git tag "${time}"
          sha=$(git rev-parse HEAD)
          echo ::set-output name=time::$time
          echo ::set-output name=sha::$sha
        fi
        echo ::set-output name=cmt::$cmt
    - name: Push changes
      uses: ad-m/github-push-action@master
      if: ${{ steps.commit.outputs.sha }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true
        directory: data
    - name: Create Release
      uses: actions/create-release@v1
      if: ${{ steps.commit.outputs.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.commit.outputs.time }}
        release_name: Release ${{ steps.commit.outputs.time }}
        body: ${{ steps.commit.outputs.time }}
        commitish: ${{ steps.commit.outputs.sha }}
